version: "3.5"
services:
  nethermind:
    build:
      context: nethermind
      args:
        UPSTREAM_VERSION: 1.29.0
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - data:/data
    environment:
      NETHERMIND_SYNCCONFIG_FASTSYNC: ""
      NETHERMIND_SYNCCONFIG_SNAPSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_NETWORKCONFIG_DISCOVERYPORT: 31804
      NETHERMIND_NETWORKCONFIG_P2PPORT: 31804
      NETHERMIND_JSONRPCCONFIG_ENGINEHOST: 0.0.0.0
      NETHERMIND_JSONRPCCONFIG_ENGINEPORT: 8551
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: "true"
      LOG: INFO
      EXTRA_OPTS: ""
    ports:
      - 31804:31804/udp
      - 31804:31804/tcp
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 16384M
    image: nethermind.holesky-nethermind.dnp.dappnode.eth:0.1.0
volumes:
  data: {}
